### ISSUE TITLE
index into maximum time list doesn't work right now

### ISSUE THREAD

**Issue by richarddun** [richarddun/util#1]
822 when checking counters:
823 nic_tot_tx_bytes - interface(LO/1)
824 nic_tot_rx_mbits - interface(LO/1)
825
826 get a value error
827
828 Traceback (most recent call last):
829   File "./constellation.py", line 156, in <module>
830     check_args()
831   File "./constellation.py", line 25, in check_args
832     curses.wrapper(main)
833   File "/usr/local/lib/python2.7/curses/wrapper.py", line 43, in wrapper
834     return func(stdscr, _args, *_kwds)
835   File "./constellation.py", line 140, in main
836     for timenotch,val in valuesource:
837   File "/usr/home/richard/python/git/util/constellation/datahandler.py", line 109, in read_full_rate_data
838     self.firstime = self.maxtimlist.index(self.shelf[countname][devn]['time'][0])
839 ValueError: 1454422736 is not in list
840
841 pdb after exception :
842
843 (Pdb) locals()
844 {'self': <datahandler.Data_build object at 0x8042ee910>, 'maxx': 189, 'maxy': 52, 'devn': 'interface(LO/1)', 'countname': 'nic_tot_rx_mbits'}
845
846 (Pdb) self.shelf[countname][devn]['time'][0]
847 1454422736
848
849 (Pdb) self.maxtimlist
850 [1454422771, 1454422778, 1454422785, 1454422792, 1454422799, 1454422806, 1454422813, 1454422820, 1454422827, 1454422834, 1454422841, 1454422848, 1454422855, 1454422862, 1454422869, 1454    422876, 1454422883, 1454422890, 1454422897, 1454422904, 1454422911, 1454422918, 1454422925, 1454422932, 1454422939, 1454422946, 1454422953, 1454422960, 1454422967, 1454422974, 145442298    1, 1454422988, 1454422995, 1454423002, 1454423009, 1454423016, 1454423023, 1454423030, 1454423037, 1454423044, 1454423051, 1454423058, 1454423065, 1454423072, 1454423079, 1454423086, 14    54423093, 1454423100, 1454423107, 1454423114, 1454423121, 1454423128, 1454423135, 1454423142, 1454423149, 1454423156, 1454423163, 1454423170, 1454423177, 1454423184, 1454423191, 1454423    198, 1454423205, 1454423212, 1454423219, 1454423226, 1454423233, 1454423240, 1454423247, 1454423254, 1454423261, 1454423268, 1454423275, 1454423282, 1454423289, 1454423296, 1454423303,     1454423310, 1454423317, 1454423324, 1454423331, 1454423338, 1454423345, 1454423352, 1454423359, 1454423366, 1454423373, 1454423380, 1454423387, 1454423394, 1454423401, 1454423408, 14544    23415, 1454423422, 1454423429, 1454423436, 1454423443, 1454423450, 1454423457, 1454423464, 1454423471, 1454423478, 1454423485, 1454423492, 1454423499, 1454423506, 1454423513, 1454423520    , 1454423527, 1454423534, 1454423541, 1454423548, 1454423555, 1454423562, 1454423569, 1454423576, 1454423583, 1454423590, 1454423597, 1454423604, 1454423611, 1454423618, 1454423625, 145    4423632, 1454423639, 1454423646, 1454423653, 1454423660, 1454423667, 1454423674, 1454423681, 1454423688, 1454423695, 1454423702, 1454423709, 1454423716, 1454423723, 1454423730, 14544237    37, 1454423744, 1454423751, 1454423758, 1454423765, 1454423772, 1454423779, 1454423786, 1454423793, 1454423800, 1454423807, 1454423814, 1454423821, 1454423828, 1454423835, 1454423842, 1    454423849, 1454423856, 1454423863, 1454423870, 1454423877, 1454423884, 1454423891, 1454423898, 1454423905, 1454423912, 1454423919, 1454423926, 1454423933, 1454423940, 1454423947, 145442    3954, 1454423961, 1454423968, 1454423975, 1454423982, 1454423989, 1454423996, 1454424003, 1454424010, 1454424017, 1454424024, 1454424031, 1454424038, 1454424045, 1454424052, 1454424059,     1454424066, 1454424073, 1454424080, 1454424087, 1454424094, 1454424101, 1454424108, 1454424115, 1454424122, 1454424129, 1454424136, 1454424143, 1454424150, 1454424157, 1454424164, 1454    424171, 1454424178, 1454424185, 1454424192, 1454424199, 1454424206, 1454424213, 1454424220, 1454424227, 1454424234, 1454424241, 1454424248, 1454424255, 1454424262, 1454424269, 145442427    6, 1454424283, 1454424290, 1454424297, 1454424304, 1454424311, 1454424318, 1454424325, 1454424332, 1454424339, 1454424346, 1454424353, 1454424360, 1454424367, 1454424374, 1454424381, 14    54424388, 1454424395, 1454424402, 1454424409, 1454424416, 1454424423, 1454424430, 1454424437, 1454424444, 1454424451, 1454424458, 1454424465, 1454424472, 1454424479, 1454424486, 1454424    493, 1454424500, 1454424507, 1454424514, 1454424521, 1454424528, 1454424535, 1454424542, 1454424549, 1454424556, 1454424563, 1454424570, 1454424577, 1454424584, 1454424591, 1454424598,     1454424605, 1454424612, 1454424619, 1454424626, 1454424633, 1454424640, 1454424647, 1454424654, 1454424661, 1454424668, 1454424675, 1454424682, 1454424689, 1454424696, 1454424703, 14544    24710, 1454424717, 1454424724, 1454424731, 1454424738, 1454424745]
851
852 as we can see, that value is not in the list.

**Comment by richarddun** [comment]
May need to do a first pass on ALL counters selected to find the longest timelen.

**Comment by richarddun** [comment]
I changed the logic of the 'get longest len' to parse every time list with a view to building the definitive 'timelist' (x axis)

However the logic says that the list is only updated if the length is longer than the previous list.  If the list isn't longer, but simply starts at an earlier time, this wouldn't be covered by current logic.

**Comment by richarddun** [comment]
solution : find a list of values that is guaranteed to not change, a baseline or 'metronome' in this case.  x axis plots fine now.
