### ISSUE TITLE
Improve performance, efficiency

### ISSUE THREAD

**Issue by richarddun** [richarddun/util#5]
In a multi-user environment (busy), due to the large number of disk i/o generated, constellation takes an extremely long time to complete on a ~200MB file.

Need to review the data flow and reduce the disk calls, optimise input.

**Comment by richarddun** [comment]
As an addition to this, a test run on a dedicated box (i7, 16GB ram) the shelve .db fails at around 147MB.

last pid: 29038;  load averages:  1.05,  0.49,  0.24                                                                                                                 up 8+21:36:36  08:13:03
34 processes:  2 running, 32 sleeping
CPU:  7.8% user,  0.0% nice,  4.9% system,  0.0% interrupt, 87.3% idle
Mem: 40M Active, 372M Inact, 983M Wired, 1760K Cache, 1708M Buf, 14G Free
Swap: 3598M Total, 3598M Free

  PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
29015 richard       1 102    0   110M 50228K CPU7    7   2:22  97.17% python2.7

last pid: 29038;  load averages:  1.10,  0.55,  0.27                                                                                                                 up 8+21:36:59  08:13:26
34 processes:  2 running, 32 sleeping
CPU:  8.1% user,  0.0% nice,  4.7% system,  0.0% interrupt, 87.3% idle
Mem: 40M Active, 374M Inact, 988M Wired, 1760K Cache, 1712M Buf, 14G Free
Swap: 3598M Total, 3598M Free

  PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
29015 richard       1 103    0   110M 52544K CPU7    7   2:45 100.00% python2.7

last pid: 29038;  load averages:  1.07,  0.58,  0.28                                                                                                                 up 8+21:37:16  08:13:43
34 processes:  2 running, 32 sleeping
CPU:  7.8% user,  0.0% nice,  4.4% system,  0.0% interrupt, 87.8% idle
Mem: 40M Active, 374M Inact, 991M Wired, 1760K Cache, 1715M Buf, 14G Free
Swap: 3598M Total, 3598M Free

  PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
29015 richard       1 103    0   110M 52572K CPU7    7   3:01 100.00% python2.7

shortly thereafter : 

Traceback (most recent call last):
  File "./constellation.py", line 162, in <module>
    check_args()
  File "./constellation.py", line 25, in check_args
    curses.wrapper(main)
  File "/usr/local/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "./constellation.py", line 49, in main
    dataspool.sync_hash()
  File "/usr/home/richard/python/git/util/constellation/datahandler.py", line 167, in sync_hash
    self.shelf.sync()
  File "/usr/local/lib/python2.7/shelve.py", line 169, in sync
    self[key] = entry
  File "/usr/local/lib/python2.7/shelve.py", line 133, in **setitem**
    self.dict[key] = f.getvalue()
dbm.error: cannot add item to database

shelve .db file is at 147MB in size

both source files (compressed) add up to 100MB

http://stackoverflow.com/questions/4995162/python-shelve-dbm-error

**Comment by richarddun** [comment]
In a previous iteration, I had set the shelve to synchronise (flush to disk) every 'n' records.  Commenting out this logic reduces run time from > 3 minutes to 18 seconds, with no other visible problems as a side effect.

Commented out lines below in constellation.py

 47     for data in log_generator:
 48         dataspool.add_data(data)
 49         #if synccount % 200 == 0:
 50         #    dataspool.sync_hash()
 51         #synccount += 1
 52     dataspool.sync_hash()
 53     dataspool.close_hash()

**Comment by richarddun** [comment]
commenting out these lines causes some data not to be written to the shelve, records are just 'skipped' and get garbage collected.

**Comment by richarddun** [comment]
Refactoring code to remove shelve sync altogether

**Comment by richarddun** [comment]
removed writeback and total runtime is down from >3 minutes to 44 seconds

**Comment by richarddun** [comment]
Removed shelve module, using in-memory dict now.  For a large input file it's counting at ~80MB RAM, but that's fine for my purposes at present.

**Comment by richarddun** [comment]
(Runtime down to 12 seconds)
